"""order_return_address_nullable

Revision ID: 529f4cf16e27
Revises: 216052c25c8c
Create Date: 2023-07-19 12:00:00.329650

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "529f4cf16e27"
down_revision = "216052c25c8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "return_address", existing_type=sa.VARCHAR(length=42), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "return_address", existing_type=sa.VARCHAR(length=42), nullable=False
    )
    # ### end Alembic commands ###
