"""add_tnx_hash_to_order

Revision ID: 216052c25c8c
Revises: c16a0c0f2053
Create Date: 2023-07-19 11:16:50.976221

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "216052c25c8c"
down_revision = "c16a0c0f2053"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("tnx_hash", sa.String(length=66), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "tnx_hash")
    # ### end Alembic commands ###
