"""init_wallet_service

Revision ID: b12db6db2361
Revises: d1aba0385f12
Create Date: 2023-06-07 15:40:24.553714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b12db6db2361"
down_revision = "d1aba0385f12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blockchain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=254), nullable=False),
        sa.Column("rpc_url", sa.String(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_blockchain_name"), "blockchain", ["name"], unique=False)
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=254), nullable=False),
        sa.Column("decimal_places", sa.SmallInteger(), nullable=False),
        sa.Column("image", sa.String(length=100), nullable=False),
        sa.Column("blockchain_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["blockchain_id"],
            ["blockchain.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
    )
    op.create_index(op.f("ix_currency_name"), "currency", ["name"], unique=False)
    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", "currency_id", name="unique_address_currency"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet")
    op.drop_index(op.f("ix_currency_name"), table_name="currency")
    op.drop_table("currency")
    op.drop_index(op.f("ix_blockchain_name"), table_name="blockchain")
    op.drop_table("blockchain")
    # ### end Alembic commands ###
